export const LOAD_HEADER = "LOAD_HEADER";
export const LOAD_MEGA_MENU_NAVIGATION = "LOAD_MEGA_MENU_NAVIGATION";
export const LOAD_MEGA_MENU_COLUMN = "LOAD_MEGA_MENU_COLUMN";
export const LOAD_MENU = "LOAD_MENU";
export const LOAD_FOOTER = "LOAD_FOOTER";
